# Generated by Django 2.1.3 on 2019-01-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aduit_userinfo',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('audit_priv', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='db_audit_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exec_user', models.CharField(max_length=20)),
                ('db_user', models.CharField(max_length=10)),
                ('req_no', models.CharField(max_length=10)),
                ('file_dir', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=1)),
                ('DescMessage', models.CharField(max_length=130)),
                ('stamp', models.CharField(max_length=12)),
            ],
        ),
    ]
