# Generated by Django 2.1.3 on 2018-12-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='db_audit_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_user', models.CharField(max_length=20)),
                ('req_no', models.CharField(max_length=10)),
                ('file_dir', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=1)),
                ('DescMessage', models.CharField(max_length=130)),
            ],
        ),
    ]
