# Generated by Django 2.1.3 on 2018-12-19 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbaudit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_audit_record',
            old_name='commit_user',
            new_name='exec_user',
        ),
        migrations.AddField(
            model_name='db_audit_record',
            name='db_user',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
