# Generated by Django 2.1.3 on 2018-12-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbaudit', '0002_auto_20181219_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_audit_record',
            name='stamp',
            field=models.CharField(default=None, max_length=12),
            preserve_default=False,
        ),
    ]
