# Generated by Django 2.1.3 on 2018-12-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbaudit', '0003_db_audit_record_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_audit_record',
            name='DescMessage',
            field=models.TextField(max_length=130),
        ),
    ]
