# Generated by Django 2.1.3 on 2018-12-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbaudit', '0004_auto_20181219_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_audit_record',
            name='DescMessage',
            field=models.CharField(max_length=130),
        ),
    ]
