# Generated by Django 2.1.3 on 2018-12-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbaudit', '0005_auto_20181219_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='aduit_userinfo',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('audit_priv', models.CharField(max_length=200)),
            ],
        ),
    ]
