# Generated by Django 2.1.3 on 2019-01-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='op_oracle_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exec_user', models.CharField(max_length=20)),
                ('req_no', models.CharField(max_length=10)),
                ('stamp', models.CharField(max_length=20)),
                ('file_dir', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='oracle_db_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env_ip', models.CharField(max_length=20)),
                ('env_port', models.CharField(max_length=5)),
                ('env_sid', models.CharField(max_length=10)),
                ('env_info', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='oracle_db_user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user_admin',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('user_priv', models.CharField(max_length=200)),
            ],
        ),
    ]
